[tool.poetry]
name = "cencer-prediction"
version = "0.1.0"
description = ""
authors = ["AbQaadir <qaadir.inbox@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
